name: Automatic Merge to Release

on:
  pull_request:
    branches:
      - hml
    types:
      - closed

jobs:
  merge_branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Merge branch into release
        run: |
          git fetch
          git checkout release
          git merge ${{ github.event.pull_request.head.ref }} --no-ff
          git push

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
