name: Pull Request Action
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - hml

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Show envs
        run: |
          git fetch
          git status
          echo "Source:: ${{toJson(github.event.pull_request.base)}}"

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{github.event.pull_request.base.head.ref}}
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "[RELEASE] ${{ github.event.pull_request.title }}"
          pr_body: "${{github.event.pull_request.body}}"
