# name: Merge any release branch to uat
# on:
#   push:
#     branches:
#       - hml
# jobs:
#   merge-branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master

#       - name: Merge staging -> uat
#         uses: devmasx/merge-branch@master
#         with:
#           type: now
#           target_branch: release
#           github_token: ${{ secrets.GITHUB_TOKEN }}

name: Pull Request Action
on:
  push:
    branches:
      - hml

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        run: echo ${{github.event}}
        with:
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_body: ${{ github.event.head_commit.message }}
          pr_title: "[TO RELEASE] ${{ github.event.pull_request.title }}"
