name: Pull Request Action
on:
  pull_request:
    branches:
      - hml
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Show envs
        run: |
          git fetch
          git status

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{github.event.pull_request.head.ref}}
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "${{ github.event.pull_request.title }}"
          pr_body: "${{github.event.pull_request.body}}"
          pr_assignee: "${{github.event.pull_request.merged_by.login}}"
          pr_label: feature
# teste cancelar
