name: Add Label on Pull Request

on:
  pull_request:
    branches:
      - hml
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'bug'
          github-token: ${{ secrets.GITHUB_TOKEN }}
