name: Add tag action
on:
  pull_request:
    branches:
      - hml
    types: [opened]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add labels based on PR title
        run: |
          git init
          git push origin HEAD:hml --push-options=--label=bug
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

