name: Add Label on Pull Request

on:
  pull_request:
    branches:
      - hml
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'bug'
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.addAssignees({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              assignees: [context.actor]
            })          
